### PR TITLE
Fixed parsing issue

### PR DESCRIPTION
**Pull request by jeanibarz**
Fixed parsing issue for filters of type "None"

### CODE REVIEW

**Comment by perivar** [comment]
Thank you!

**Comment by jeanibarz** [comment]
You're welcome !

**Comment by perivar** [comment]
Hi,
I am happy to merge in any changes you to to extend the tool.
But I suggest you try out SharpDevelop which I am using, which do support
the form design.
It's actually quite good, except that you cannot do 64 but debugging, but
that's OK for me.
http://www.icsharpcode.net/opensource/sd/
(I am in no way affiliated with them, it's just the IDE I have been using
the last 5 years since I don't want to pay for Visual Studio).

Cheers,
Per Ivar

**Comment by jeanibarz** [comment]
Thank you very much for the tip : 'll try it out !
Le 28 juil. 2015 10:18, "Per Ivar Nerseth" notifications@github.com a
écrit :

**Pull request merged**
